### ISSUE TITLE
Skip some message

### ISSUE THREAD

**Issue by Davabbb** [koide3/livox_to_pointcloud2#2]
did someone have that not all messages were converted to point cloud 2 and what could be the problem?

**Comment by Davabbb** [comment]
@koide3

**Comment by koide3** [comment]
If you are using ROS2, it is a common issue unfortunately. ROS2 has several communication-related issues, and they have not been fixed yet. In that case, [the composition mechanism](https://docs.ros.org/en/foxy/Concepts/About-Composition.html) would be helpful to reduce the bandwidth.

**Comment by Davabbb** [comment]
@koide3 you can use a different approach, I was able to make a Custom Msg <-> Point Cloud 2 without losing messages, use this https://ternaris.gitlab.io/rosbags/
